In [1]:
import pandas as pd
import pandera as pa

In [2]:
valores_ausentes = ['**','###!','####','****','*****','NULL']
df = pd.read_csv("ocorrencia.csv", parse_dates=["ocorrencia_dia"], dayfirst=True, na_values=valores_ausentes)
df.head(10)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,52242,52242,INCIDENTE,PORTO ALEGRE,RS,SBPA,2012-05-01,20:27:00,0
1,45331,45331,ACIDENTE,GUARULHOS,SP,SBGR,2012-06-01,13:44:00,3
2,45333,45333,ACIDENTE,VIAMÃO,RS,NaN,2012-06-01,13:00:00,0
3,45401,45401,ACIDENTE,SÃO SEBASTIÃO,SP,NaN,2012-06-01,17:00:00,0
4,45407,45407,ACIDENTE,SÃO SEPÉ,RS,NaN,2012-06-01,16:30:00,0
5,52243,52243,INCIDENTE,UBATUBA,SP,NaN,2012-06-01,14:30:00,0
6,50713,50713,INCIDENTE GRAVE,CAMPINAS,SP,SDAI,2012-07-01,18:15:00,0
7,45334,45334,INCIDENTE,BELÉM,PA,SBBE,2012-08-01,19:12:00,0
8,45391,45391,ACIDENTE,CONCEIÇÃO DAS ALAGOAS,MG,NaN,2012-08-01,16:00:00,0
9,52244,52244,INCIDENTE,UBERLÂNDIA,MG,SBUL,2012-08-01,22:13:00,0

In [3]:
schema = pa.DataFrameSchema(
    columns = {
        "codigo_ocorrencia":pa.Column(pa.Int),
        "codigo_ocorrencia2":pa.Column(pa.Int),
        "ocorrencia_classificacao":pa.Column(pa.String),
        "ocorrencia_cidade":pa.Column(pa.String),
        "ocorrencia_uf":pa.Column(pa.String, pa.Check.str_length(2,2), nullable=True),
        "ocorrencia_aerodromo":pa.Column(pa.String, nullable=True),
        "ocorrencia_dia":pa.Column(pa.DateTime),
        "ocorrencia_hora":pa.Column(pa.String, pa.Check.str_matches(r'^[0-1]?[0-9]|[0-3]:([0-5][0-9])(:[0-5][0-9])?$'), nullable=True),
        "total_recomendacoes":pa.Column(pa.Int)
    }
)

In [4]:
schema.validate(df)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,52242,52242,INCIDENTE,PORTO ALEGRE,RS,SBPA,2012-05-01,20:27:00,0
1,45331,45331,ACIDENTE,GUARULHOS,SP,SBGR,2012-06-01,13:44:00,3
2,45333,45333,ACIDENTE,VIAMÃO,RS,NaN,2012-06-01,13:00:00,0
3,45401,45401,ACIDENTE,SÃO SEBASTIÃO,SP,NaN,2012-06-01,17:00:00,0
4,45407,45407,ACIDENTE,SÃO SEPÉ,RS,NaN,2012-06-01,16:30:00,0
...,...,...,...,...,...,...,...,...,...
5162,80458,80458,ACIDENTE,JATAÍ,GO,NaN,2021-12-30,20:30:00,0
5163,80452,80452,ACIDENTE,MARACAÍ,SP,NaN,2021-12-31,9:30:00,0
5164,80457,80457,INCIDENTE GRAVE,NOVO HAMBURGO,RS,SSNH,2021-12-31,11:59:00,0
5165,80460,80460,INCIDENTE,CURITIBA,PR,SBBI,2021-12-31,15:12:00,0
5166,80467,80467,INCIDENTE,PETROLINA,PE,SBPL,2021-12-31,20:30:00,0

In [5]:
df.dtypes

codigo_ocorrencia                    int64
codigo_ocorrencia2                   int64
ocorrencia_classificacao            object
ocorrencia_cidade                   object
ocorrencia_uf                       object
ocorrencia_aerodromo                object
ocorrencia_dia              datetime64[ns]
ocorrencia_hora                     object
total_recomendacoes                  int64
dtype: object

In [6]:
df.iloc[-1]

codigo_ocorrencia                         80467
codigo_ocorrencia2                        80467
ocorrencia_classificacao              INCIDENTE
ocorrencia_cidade                     PETROLINA
ocorrencia_uf                                PE
ocorrencia_aerodromo                       SBPL
ocorrencia_dia              2021-12-31 00:00:00
ocorrencia_hora                        20:30:00
total_recomendacoes                           0
Name: 5166, dtype: object

In [7]:
df.tail()

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
5162,80458,80458,ACIDENTE,JATAÍ,GO,NaN,2021-12-30,20:30:00,0
5163,80452,80452,ACIDENTE,MARACAÍ,SP,NaN,2021-12-31,9:30:00,0
5164,80457,80457,INCIDENTE GRAVE,NOVO HAMBURGO,RS,SSNH,2021-12-31,11:59:00,0
5165,80460,80460,INCIDENTE,CURITIBA,PR,SBBI,2021-12-31,15:12:00,0
5166,80467,80467,INCIDENTE,PETROLINA,PE,SBPL,2021-12-31,20:30:00,0

In [8]:
df.iloc[10:15]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
10,45332,45332,ACIDENTE,VIAMÃO,RS,NaN,2012-09-01,13:30:00,0
11,52245,52245,INCIDENTE,PORTO ALEGRE,RS,SBPA,2012-09-01,13:36:00,0
12,45396,45396,INCIDENTE GRAVE,MARABÁ,PA,SBMA,2012-11-01,11:21:00,0
13,45408,45408,ACIDENTE,ELDORADO,SP,NaN,2012-11-01,13:45:00,1
14,45447,45447,INCIDENTE,RIO BRANCO,AC,NaN,2012-01-13,18:15:00,0

In [9]:
df.loc[10:15]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
10,45332,45332,ACIDENTE,VIAMÃO,RS,NaN,2012-09-01,13:30:00,0
11,52245,52245,INCIDENTE,PORTO ALEGRE,RS,SBPA,2012-09-01,13:36:00,0
12,45396,45396,INCIDENTE GRAVE,MARABÁ,PA,SBMA,2012-11-01,11:21:00,0
13,45408,45408,ACIDENTE,ELDORADO,SP,NaN,2012-11-01,13:45:00,1
14,45447,45447,INCIDENTE,RIO BRANCO,AC,NaN,2012-01-13,18:15:00,0
15,45409,45409,ACIDENTE,CÁCERES,MT,NaN,2012-01-14,10:00:00,0

In [10]:
df.loc[:,'ocorrencia_uf']

0       RS
1       SP
2       RS
3       SP
4       RS
        ..
5162    GO
5163    SP
5164    RS
5165    PR
5166    PE
Name: ocorrencia_uf, Length: 5167, dtype: object

In [11]:
df['ocorrencia_uf']

0       RS
1       SP
2       RS
3       SP
4       RS
        ..
5162    GO
5163    SP
5164    RS
5165    PR
5166    PE
Name: ocorrencia_uf, Length: 5167, dtype: object

In [12]:
df.isna().sum()

codigo_ocorrencia              0
codigo_ocorrencia2             0
ocorrencia_classificacao       0
ocorrencia_cidade              0
ocorrencia_uf                  2
ocorrencia_aerodromo        1905
ocorrencia_dia                 0
ocorrencia_hora                1
total_recomendacoes            0
dtype: int64

In [13]:
df.isnull().sum()

codigo_ocorrencia              0
codigo_ocorrencia2             0
ocorrencia_classificacao       0
ocorrencia_cidade              0
ocorrencia_uf                  2
ocorrencia_aerodromo        1905
ocorrencia_dia                 0
ocorrencia_hora                1
total_recomendacoes            0
dtype: int64

In [14]:
filtro = df.ocorrencia_uf.isnull()
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
1099,49474,49474,ACIDENTE,ÁGUAS INTERNACIONAIS,NaN,NaN,2013-02-09,2:54:00,0
4728,79956,79956,ACIDENTE,NÃO IDENTIFICADA,NaN,NaN,2021-02-26,11:00:00,0

In [15]:
filtro = df.ocorrencia_aerodromo.isnull()
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
2,45333,45333,ACIDENTE,VIAMÃO,RS,NaN,2012-06-01,13:00:00,0
3,45401,45401,ACIDENTE,SÃO SEBASTIÃO,SP,NaN,2012-06-01,17:00:00,0
4,45407,45407,ACIDENTE,SÃO SEPÉ,RS,NaN,2012-06-01,16:30:00,0
5,52243,52243,INCIDENTE,UBATUBA,SP,NaN,2012-06-01,14:30:00,0
8,45391,45391,ACIDENTE,CONCEIÇÃO DAS ALAGOAS,MG,NaN,2012-08-01,16:00:00,0
...,...,...,...,...,...,...,...,...,...
5151,80446,80446,ACIDENTE,JACAREACANGA,PA,NaN,2021-12-20,17:10:00,0
5155,80450,80450,ACIDENTE,DOURADOS,MS,NaN,2021-12-28,10:30:00,0
5159,80455,80455,INCIDENTE GRAVE,SANTA RITA,PB,NaN,2021-12-29,18:50:00,0
5162,80458,80458,ACIDENTE,JATAÍ,GO,NaN,2021-12-30,20:30:00,0
5163,80452,80452,ACIDENTE,MARACAÍ,SP,NaN,2021-12-31,9:30:00,0

In [16]:
filtro = df.ocorrencia_hora.isnull()
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
2974,78823,78823,INCIDENTE,CORUMBÁ,MS,NaN,2017-09-07,NaN,0

In [17]:
df.count()

codigo_ocorrencia           5167
codigo_ocorrencia2          5167
ocorrencia_classificacao    5167
ocorrencia_cidade           5167
ocorrencia_uf               5165
ocorrencia_aerodromo        3262
ocorrencia_dia              5167
ocorrencia_hora             5166
total_recomendacoes         5167
dtype: int64

In [18]:
#ocorrências com mais de 10 recomendações
filtro = df.total_recomendacoes > 10
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
844,47938,47938,INCIDENTE,BRASÍLIA,DF,SBBR,2013-04-13,18:00:00,11
1669,52265,52265,ACIDENTE,SANTOS,SP,NaN,2014-08-13,13:03:00,13
2804,66432,66432,INCIDENTE GRAVE,VITÓRIA,ES,NaN,2017-02-21,11:47:00,12

In [19]:
#ocorrências com mais de 10 recomendações
filtro = df.total_recomendacoes > 10
df.loc[filtro, ['ocorrencia_cidade', 'total_recomendacoes']]

     ocorrencia_cidade  total_recomendacoes
844           BRASÍLIA                   11
1669            SANTOS                   13
2804           VITÓRIA                   12

In [20]:
#ocorrências cuja classificação == INCIDENTE GRAVE
filtro = df.ocorrencia_classificacao == 'INCIDENTE GRAVE'
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
6,50713,50713,INCIDENTE GRAVE,CAMPINAS,SP,SDAI,2012-07-01,18:15:00,0
12,45396,45396,INCIDENTE GRAVE,MARABÁ,PA,SBMA,2012-11-01,11:21:00,0
18,50714,50714,INCIDENTE GRAVE,CAMOCIM,CE,SNWC,2012-01-17,18:25:00,0
19,45399,45399,INCIDENTE GRAVE,MUANÁ,PA,NaN,2012-01-18,17:35:00,0
24,45582,45582,INCIDENTE GRAVE,RONDONÓPOLIS,MT,SWRD,2012-01-20,17:00:00,0
...,...,...,...,...,...,...,...,...,...
5139,80427,80427,INCIDENTE GRAVE,NOVA BANDEIRANTES,MT,NaN,2021-12-12,17:20:00,0
5146,80448,80448,INCIDENTE GRAVE,FORMOSO DO ARAGUAIA,TO,NaN,2021-12-18,19:00:00,0
5158,80454,80454,INCIDENTE GRAVE,ARAÇATUBA,SP,SBAU,2021-12-29,21:35:00,0
5159,80455,80455,INCIDENTE GRAVE,SANTA RITA,PB,NaN,2021-12-29,18:50:00,0
5164,80457,80457,INCIDENTE GRAVE,NOVO HAMBURGO,RS,SSNH,2021-12-31,11:59:00,0

In [21]:
#ocorrências cuja classificação == INCIDENTE GRAVE e o estado == SP
filtro1 = df.ocorrencia_classificacao == 'INCIDENTE GRAVE'
filtro2 = df.ocorrencia_uf == 'SP'
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
6,50713,50713,INCIDENTE GRAVE,CAMPINAS,SP,SDAI,2012-07-01,18:15:00,0
78,45598,45598,INCIDENTE GRAVE,BRAGANÇA PAULISTA,SP,SBBP,2012-02-20,14:10:00,0
86,45653,45653,INCIDENTE GRAVE,GUARULHOS,SP,SBGR,2012-02-24,20:04:00,0
91,45599,45599,INCIDENTE GRAVE,BRAGANÇA PAULISTA,SP,SBBP,2012-02-27,19:15:00,0
140,45651,45651,INCIDENTE GRAVE,ITU,SP,NaN,2012-03-24,20:45:00,1
...,...,...,...,...,...,...,...,...,...
4954,80200,80200,INCIDENTE GRAVE,BRAGANÇA PAULISTA,SP,SDVH,2021-07-25,12:25:00,0
4980,80238,80238,INCIDENTE GRAVE,VOTUPORANGA,SP,SDVG,2021-11-08,19:09:00,0
5003,80265,80265,INCIDENTE GRAVE,SÃO PAULO,SP,SBMT,2021-08-31,16:50:00,0
5098,80382,80382,INCIDENTE GRAVE,PIRACICABA,SP,SDPW,2021-11-16,20:50:00,0
5158,80454,80454,INCIDENTE GRAVE,ARAÇATUBA,SP,SBAU,2021-12-29,21:35:00,0

In [22]:
#ocorrências cuja classificação == INCIDENTE GRAVE ou o estado == SP
filtro1 = df.ocorrencia_classificacao == 'INCIDENTE GRAVE'
filtro2 = df.ocorrencia_uf == 'SP'
df.loc[filtro1 | filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
1,45331,45331,ACIDENTE,GUARULHOS,SP,SBGR,2012-06-01,13:44:00,3
3,45401,45401,ACIDENTE,SÃO SEBASTIÃO,SP,NaN,2012-06-01,17:00:00,0
5,52243,52243,INCIDENTE,UBATUBA,SP,NaN,2012-06-01,14:30:00,0
6,50713,50713,INCIDENTE GRAVE,CAMPINAS,SP,SDAI,2012-07-01,18:15:00,0
12,45396,45396,INCIDENTE GRAVE,MARABÁ,PA,SBMA,2012-11-01,11:21:00,0
...,...,...,...,...,...,...,...,...,...
5158,80454,80454,INCIDENTE GRAVE,ARAÇATUBA,SP,SBAU,2021-12-29,21:35:00,0
5159,80455,80455,INCIDENTE GRAVE,SANTA RITA,PB,NaN,2021-12-29,18:50:00,0
5161,80456,80456,INCIDENTE,SÃO PAULO,SP,SBSP,2021-12-30,13:15:00,0
5163,80452,80452,ACIDENTE,MARACAÍ,SP,NaN,2021-12-31,9:30:00,0
5164,80457,80457,INCIDENTE GRAVE,NOVO HAMBURGO,RS,SSNH,2021-12-31,11:59:00,0

In [23]:
#ocorrências cuja classificação == INCIDENTE GRAVE ou o classificação == INCIDENTE e o estado == SP
filtro1 = df.ocorrencia_classificacao.isin(['INCIDENTE GRAVE', 'INCIDENTE'])
filtro2 = df.ocorrencia_uf == 'SP'
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
5,52243,52243,INCIDENTE,UBATUBA,SP,NaN,2012-06-01,14:30:00,0
6,50713,50713,INCIDENTE GRAVE,CAMPINAS,SP,SDAI,2012-07-01,18:15:00,0
28,52248,52248,INCIDENTE,SÃO PAULO,SP,SBMT,2012-01-21,11:15:00,0
35,52054,52054,INCIDENTE,SÃO PAULO,SP,SBMT,2012-01-25,23:00:00,0
36,52055,52055,INCIDENTE,RIBEIRÃO PRETO,SP,NaN,2012-01-25,9:30:00,0
...,...,...,...,...,...,...,...,...,...
5134,80425,80425,INCIDENTE,SÃO PAULO,SP,SBSP,2021-09-12,20:30:00,0
5143,80431,80431,INCIDENTE,SANTOS,SP,SBST,2021-12-15,12:30:00,0
5157,80453,80453,INCIDENTE,CAMPINAS,SP,SBKP,2021-12-29,9:00:00,0
5158,80454,80454,INCIDENTE GRAVE,ARAÇATUBA,SP,SBAU,2021-12-29,21:35:00,0
5161,80456,80456,INCIDENTE,SÃO PAULO,SP,SBSP,2021-12-30,13:15:00,0

In [24]:
#ocorrências cuja cidade comece com a letra C
filtro = df.ocorrencia_cidade.str[0] ==  'C'
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
6,50713,50713,INCIDENTE GRAVE,CAMPINAS,SP,SDAI,2012-07-01,18:15:00,0
8,45391,45391,ACIDENTE,CONCEIÇÃO DAS ALAGOAS,MG,NaN,2012-08-01,16:00:00,0
15,45409,45409,ACIDENTE,CÁCERES,MT,NaN,2012-01-14,10:00:00,0
18,50714,50714,INCIDENTE GRAVE,CAMOCIM,CE,SNWC,2012-01-17,18:25:00,0
22,45390,45390,ACIDENTE,CACHOEIRA DOURADA,GO,NaN,2012-01-20,21:00:00,0
...,...,...,...,...,...,...,...,...,...
5142,80434,80434,ACIDENTE,CARACOL,MS,NaN,2021-12-14,21:35:00,0
5144,80447,80447,INCIDENTE,CONFINS,MG,SBCF,2021-12-15,17:10:00,0
5150,80445,80445,ACIDENTE,CHUPINGUAIA,RO,NaN,2021-12-20,12:05:00,0
5157,80453,80453,INCIDENTE,CAMPINAS,SP,SBKP,2021-12-29,9:00:00,0
5165,80460,80460,INCIDENTE,CURITIBA,PR,SBBI,2021-12-31,15:12:00,0

In [25]:
#ocorrências cuja cidade termine com a letra A
filtro = df.ocorrencia_cidade.str[-1] ==  'A'
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
5,52243,52243,INCIDENTE,UBATUBA,SP,NaN,2012-06-01,14:30:00,0
9,52244,52244,INCIDENTE,UBERLÂNDIA,MG,SBUL,2012-08-01,22:13:00,0
17,52246,52246,INCIDENTE,BRASÍLIA,DF,SBBR,2012-01-16,16:47:00,0
21,45392,45392,ACIDENTE,BRASÍLIA,DF,NaN,2012-01-19,21:30:00,2
22,45390,45390,ACIDENTE,CACHOEIRA DOURADA,GO,NaN,2012-01-20,21:00:00,0
...,...,...,...,...,...,...,...,...,...
5152,80465,80465,INCIDENTE,VITÓRIA,ES,SBVT,2021-12-21,22:25:00,0
5158,80454,80454,INCIDENTE GRAVE,ARAÇATUBA,SP,SBAU,2021-12-29,21:35:00,0
5159,80455,80455,INCIDENTE GRAVE,SANTA RITA,PB,NaN,2021-12-29,18:50:00,0
5165,80460,80460,INCIDENTE,CURITIBA,PR,SBBI,2021-12-31,15:12:00,0
5166,80467,80467,INCIDENTE,PETROLINA,PE,SBPL,2021-12-31,20:30:00,0

In [26]:
#ocorrências cuja cidade termine com os caracteres IM
filtro = df.ocorrencia_cidade.str[-2:] ==  'IM'
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
18,50714,50714,INCIDENTE GRAVE,CAMOCIM,CE,SNWC,2012-01-17,18:25:00,0
227,45861,45861,INCIDENTE,PARNAMIRIM,RN,SBNT,2012-05-19,10:40:00,0
374,46260,46260,ACIDENTE,TARUMIRIM,MG,NaN,2012-08-14,19:50:00,1
674,46881,46881,INCIDENTE,BIRITIBA-MIRIM,SP,SDIH,2013-01-18,18:10:00,0
783,47142,47142,ACIDENTE,ALMEIRIM,PA,SBMD,2013-12-03,12:30:00,3
803,47333,47333,INCIDENTE GRAVE,BIRITIBA-MIRIM,SP,SDIH,2013-03-22,18:45:00,0
977,49515,49515,INCIDENTE,PARNAMIRIM,RN,NaN,2013-06-18,13:30:00,0
995,49157,49157,INCIDENTE GRAVE,ERECHIM,RS,SSER,2013-06-28,15:25:00,0
1092,49617,49617,INCIDENTE GRAVE,CACHOEIRO DE ITAPEMIRIM,ES,SNKI,2013-08-31,13:00:00,0
1119,49641,49641,INCIDENTE,JARDIM,MS,SSJI,2013-09-14,13:53:00,0
1215,50511,50511,INCIDENTE GRAVE,ALMEIRIM,PA,NaN,2013-10-11,12:30:00,1
1219,50334,50334,ACIDENTE,GUARAMIRIM,SC,NaN,2013-11-14,19:00:00,0
1225,50276,50276,INCIDENTE,BIRITIBA-MIRIM,SP,NaN,2013-11-20,15:30:00,0
1237,50339,50339,ACIDENTE,MOGI MIRIM,SP,NaN,2013-11-29,19:30:00,0
1368,53150,53150,ACIDENTE,MOGI MIRIM,SP,SDMJ,2014-01-31,21:00:00,0
1718,52282,52282,ACIDENTE,BOA VISTA DO TUPIM,BA,NaN,2014-09-15,18:15:00,0
2001,53177,53177,ACIDENTE,CEARÁ-MIRIM,RN,SNOG,2015-04-04,20:15:00,0
2217,53555,53555,ACIDENTE,CEARÁ-MIRIM,RN,SNOG,2015-09-23,13:00:00,0
2253,53543,53543,ACIDENTE,JARDIM,MS,SSJI,2015-10-21,14:30:00,0
2569,65492,65492,INCIDENTE,NOVO SÃO JOAQUIM,MT,SDZX,2016-07-24,9:00:00,0
2570,65491,65491,INCIDENTE,NOVO SÃO JOAQUIM,MT,NaN,2016-07-25,15:00:00,0
2644,65809,65809,ACIDENTE,MOGI MIRIM,SP,SDMJ,2016-11-10,16:15:00,0
2723,66094,66094,INCIDENTE GRAVE,ERECHIM,RS,NaN,2016-10-12,14:30:00,1
2760,66272,66272,ACIDENTE,MOGI MIRIM,SP,SDMJ,2017-01-15,11:00:00,0
2763,66278,66278,ACIDENTE,CAMOCIM,CE,NaN,2017-01-18,9:45:00,0
2927,66800,66800,ACIDENTE,COXIM,MS,NaN,2017-05-28,15:40:00,0
2955,66911,66911,ACIDENTE,BONFIM,RR,SSJL,2017-06-21,21:00:00,0
3085,77429,77429,ACIDENTE,BONFIM,RR,NaN,2017-10-16,11:40:00,0
3159,77249,77249,INCIDENTE GRAVE,ERECHIM,RS,SSER,2017-09-12,13:18:00,0
3498,78183,78183,ACIDENTE,IPUMIRIM,SC,NaN,2018-09-15,15:00:00,2
3592,78375,78375,ACIDENTE,ALMEIRIM,PA,NaN,2018-02-12,15:00:00,0
3600,78357,78357,INCIDENTE,BIRITIBA-MIRIM,SP,SDIH,2018-11-12,14:03:00,0
3700,78551,78551,ACIDENTE,BIRITIBA-MIRIM,SP,SDIH,2019-02-23,22:00:00,0
3741,78612,78612,ACIDENTE,BIRITIBA-MIRIM,SP,SDIH,2019-03-23,15:30:00,1
3766,78661,78661,ACIDENTE,ALMEIRIM,PA,NaN,2019-12-04,16:00:00,0
3846,78749,78749,ACIDENTE,CAMOCIM,CE,SNWC,2019-06-27,14:30:00,0
4127,79134,79134,INCIDENTE,ERECHIM,RS,SSER,2020-09-01,20:52:00,0
4331,79454,79454,INCIDENTE GRAVE,GUARAMIRIM,SC,SJVL,2020-05-25,20:30:00,0
4367,79414,79414,ACIDENTE,BIRITIBA-MIRIM,SP,SDIH,2020-06-24,13:50:00,0
4522,79627,79627,ACIDENTE,BIRITIBA-MIRIM,SP,SDIH,2020-10-24,18:50:00,0
4673,79866,79866,ACIDENTE,ALMEIRIM,PA,NaN,2021-01-28,15:55:00,0
4756,79973,79973,ACIDENTE,ERECHIM,RS,NaN,2021-03-14,14:35:00,0
4757,79981,79981,INCIDENTE,ALMEIRIM,PA,SBMD,2021-03-14,17:05:00,0
5011,80273,80273,ACIDENTE,BIRITIBA-MIRIM,SP,NaN,2021-06-09,14:35:00,0

In [28]:
#ocorrências cuja cidade contenha os caracteres CEA
filtro = df.ocorrencia_cidade.str.contains('CEA')
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
2001,53177,53177,ACIDENTE,CEARÁ-MIRIM,RN,SNOG,2015-04-04,20:15:00,0
2217,53555,53555,ACIDENTE,CEARÁ-MIRIM,RN,SNOG,2015-09-23,13:00:00,0

In [29]:
#ocorrências cuja cidade contenha os caracteres CE ou IM
filtro = df.ocorrencia_cidade.str.contains('CE|IM')
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
8,45391,45391,ACIDENTE,CONCEIÇÃO DAS ALAGOAS,MG,NaN,2012-08-01,16:00:00,0
15,45409,45409,ACIDENTE,CÁCERES,MT,NaN,2012-01-14,10:00:00,0
18,50714,50714,INCIDENTE GRAVE,CAMOCIM,CE,SNWC,2012-01-17,18:25:00,0
145,52057,52057,INCIDENTE,MACEIÓ,AL,SBMO,2012-03-26,13:19:00,0
227,45861,45861,INCIDENTE,PARNAMIRIM,RN,SBNT,2012-05-19,10:40:00,0
...,...,...,...,...,...,...,...,...,...
4757,79981,79981,INCIDENTE,ALMEIRIM,PA,SBMD,2021-03-14,17:05:00,0
4817,80052,80052,INCIDENTE,PRIMAVERA DO LESTE,MT,NaN,2021-04-24,9:50:00,0
4969,80252,80252,ACIDENTE,IRACEMA,RR,NaN,2021-04-08,11:45:00,0
5011,80273,80273,ACIDENTE,BIRITIBA-MIRIM,SP,NaN,2021-06-09,14:35:00,0
5127,80418,80418,ACIDENTE,VERÍSSIMO,MG,NaN,2021-07-12,11:10:00,0

In [30]:
#ocorrências do ano de 2015
filtro = df.ocorrencia_dia.dt.year == 2015
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
1870,52992,52992,INCIDENTE GRAVE,SALVADOR,BA,SBSV,2015-01-01,11:40:00,3
1871,52979,52979,ACIDENTE,IVINHEMA,MS,NaN,2015-02-01,14:50:00,0
1872,53073,53073,INCIDENTE,TEFÉ,AM,SBTF,2015-02-01,16:28:00,0
1873,53074,53074,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-02-01,20:34:00,0
1874,52976,52976,ACIDENTE,TOLEDO,PR,SBTD,2015-04-01,22:04:00,6
...,...,...,...,...,...,...,...,...,...
2336,60632,60632,INCIDENTE GRAVE,ITABERÁ,SP,NaN,2015-12-24,14:00:00,0
2337,60600,60600,INCIDENTE,GUARULHOS,SP,SBGR,2015-12-25,19:00:00,0
2338,60642,60642,INCIDENTE,SÃO FRANCISCO DO SUL,SC,SSSS,2015-12-26,16:00:00,0
2339,60631,60631,ACIDENTE,MAÇAMBARÁ,RS,NaN,2015-12-28,19:00:00,2
2340,60649,60649,ACIDENTE,PORTO BELO,SC,SDEN,2015-12-31,14:00:00,0

In [31]:
#ocorrências do ano de 2015 e mês 9
filtro1 = df.ocorrencia_dia.dt.year == 2015
filtro2 = df.ocorrencia_dia.dt.month == 9
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
1880,52994,52994,INCIDENTE,SÃO PAULO,SP,SBMT,2015-09-01,23:25:00,0
1932,52995,52995,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2015-09-02,10:00:00,0
1933,53000,53000,INCIDENTE,PORTO ALEGRE,RS,NaN,2015-09-02,9:00:00,0
2016,53204,53204,INCIDENTE GRAVE,ANÁPOLIS,GO,SWNS,2015-09-04,13:13:00,3
2017,53208,53208,INCIDENTE,SÃO PAULO,SP,SBMT,2015-09-04,19:20:00,0
2052,53255,53255,ACIDENTE,NOVO PROGRESSO,PA,SJNP,2015-09-05,17:30:00,0
2053,53258,53258,ACIDENTE,PARECI NOVO,RS,SSNG,2015-09-05,14:00:00,0
2054,53261,53261,ACIDENTE,MIRASSOL D'OESTE,MT,NaN,2015-09-05,20:00:00,0
2055,53285,53285,INCIDENTE,BELÉM,PA,SBBE,2015-09-05,12:53:00,0
2089,53308,53308,INCIDENTE GRAVE,SÃO LUÍS,MA,SBSL,2015-09-06,16:05:00,1
2127,53359,53359,ACIDENTE,TATUÍ,SP,SDTF,2015-09-07,16:15:00,0
2162,53424,53424,INCIDENTE,CURITIBA,PR,SBCT,2015-09-08,17:35:00,0
2163,53465,53465,ACIDENTE,PIRACANJUBA,GO,NaN,2015-09-08,12:30:00,0
2197,53480,53480,INCIDENTE,CONFINS,MG,SBCF,2015-09-09,14:00:00,0
2199,53474,53474,ACIDENTE,BELÉM,PA,NaN,2015-09-13,13:17:00,0
2200,53550,53550,ACIDENTE,ITAPIPOCA,CE,NaN,2015-09-13,9:20:00,0
2201,53594,53594,INCIDENTE,CABO FRIO,RJ,SBCB,2015-09-14,13:00:00,0
2202,53608,53608,INCIDENTE,FLORIANÓPOLIS,SC,SBFL,2015-09-14,20:30:00,0
2203,53592,53592,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-09-15,14:50:00,0
2204,53593,53593,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-09-15,13:37:00,0
2205,53484,53484,ACIDENTE,ANGRA DOS REIS,RJ,NaN,2015-09-18,13:30:00,0
2206,53486,53486,ACIDENTE,GOIÂNIA,GO,SBGO,2015-09-19,13:20:00,1
2207,53487,53487,ACIDENTE,SANTA RITA DE CÁSSIA,BA,NaN,2015-09-19,20:30:00,0
2208,53482,53482,ACIDENTE,PIRENÓPOLIS,GO,SNMH,2015-09-20,21:10:00,0
2209,53483,53483,INCIDENTE,JUNDIAÍ,SP,SBJD,2015-09-20,21:05:00,0
2210,53485,53485,ACIDENTE,CASA BRANCA,SP,NaN,2015-09-20,17:30:00,0
2211,53606,53606,INCIDENTE,CARAUARI,AM,SWCA,2015-09-20,10:54:00,0
2212,53607,53607,INCIDENTE,RECIFE,PE,SBRF,2015-09-21,14:40:00,0
2213,53489,53489,ACIDENTE,JACAREACANGA,PA,SBEK,2015-09-22,22:15:00,0
2214,53506,53506,INCIDENTE,FOZ DO IGUAÇU,PR,SBFI,2015-09-22,15:57:00,0
2215,53488,53488,ACIDENTE,MACEIÓ,AL,NaN,2015-09-23,14:00:00,6
2216,53507,53507,INCIDENTE,FOZ DO IGUAÇU,PR,SBFI,2015-09-23,20:00:00,0
2217,53555,53555,ACIDENTE,CEARÁ-MIRIM,RN,SNOG,2015-09-23,13:00:00,0
2218,53554,53554,ACIDENTE,SANTA ROSA,RS,SSZR,2015-09-24,17:00:00,0
2219,53558,53558,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2015-09-25,22:15:00,0
2220,53610,53610,INCIDENTE,BAURU,SP,NaN,2015-09-25,10:08:00,0
2221,53503,53503,INCIDENTE,SANTARÉM,PA,SBSN,2015-09-26,11:45:00,0
2222,53495,53495,ACIDENTE,SANTO ANTÔNIO DO LEVERGER,MT,SWLV,2015-09-28,21:10:00,1
2223,53498,53498,ACIDENTE,ALTA FLORESTA,MT,NaN,2015-09-28,14:40:00,0
2224,53553,53553,ACIDENTE,TRAJANO DE MORAES,RJ,NaN,2015-09-28,18:30:00,0
2225,53609,53609,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2015-09-28,15:35:00,0
2226,53490,53490,INCIDENTE,SALVADOR,BA,SBSV,2015-09-30,4:30:00,0
2227,53491,53491,ACIDENTE,PAUINI,AM,NaN,2015-09-30,14:30:00,0
2228,53496,53496,INCIDENTE GRAVE,JATAÍ,GO,SWJW,2015-09-30,17:34:00,1
2229,53508,53508,INCIDENTE,FOZ DO IGUAÇU,PR,SBFI,2015-09-30,18:38:00,0
2230,53532,53532,INCIDENTE,GOIÂNIA,GO,SBGO,2015-09-30,11:55:00,0
2278,53563,53563,INCIDENTE GRAVE,TAIPU,RN,NaN,2015-09-11,20:00:00,0
2279,53564,53564,ACIDENTE,BALSAS,MA,SNBS,2015-09-11,19:30:00,4
2280,53566,53566,ACIDENTE,LENÇÓIS PAULISTA,SP,NaN,2015-09-11,19:30:00,0

In [32]:
#ocorrências do ano de 2015 e mês 9
filtro = (df.ocorrencia_dia.dt.year == 2015) & (df.ocorrencia_dia.dt.month == 9)
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
1880,52994,52994,INCIDENTE,SÃO PAULO,SP,SBMT,2015-09-01,23:25:00,0
1932,52995,52995,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2015-09-02,10:00:00,0
1933,53000,53000,INCIDENTE,PORTO ALEGRE,RS,NaN,2015-09-02,9:00:00,0
2016,53204,53204,INCIDENTE GRAVE,ANÁPOLIS,GO,SWNS,2015-09-04,13:13:00,3
2017,53208,53208,INCIDENTE,SÃO PAULO,SP,SBMT,2015-09-04,19:20:00,0
2052,53255,53255,ACIDENTE,NOVO PROGRESSO,PA,SJNP,2015-09-05,17:30:00,0
2053,53258,53258,ACIDENTE,PARECI NOVO,RS,SSNG,2015-09-05,14:00:00,0
2054,53261,53261,ACIDENTE,MIRASSOL D'OESTE,MT,NaN,2015-09-05,20:00:00,0
2055,53285,53285,INCIDENTE,BELÉM,PA,SBBE,2015-09-05,12:53:00,0
2089,53308,53308,INCIDENTE GRAVE,SÃO LUÍS,MA,SBSL,2015-09-06,16:05:00,1
2127,53359,53359,ACIDENTE,TATUÍ,SP,SDTF,2015-09-07,16:15:00,0
2162,53424,53424,INCIDENTE,CURITIBA,PR,SBCT,2015-09-08,17:35:00,0
2163,53465,53465,ACIDENTE,PIRACANJUBA,GO,NaN,2015-09-08,12:30:00,0
2197,53480,53480,INCIDENTE,CONFINS,MG,SBCF,2015-09-09,14:00:00,0
2199,53474,53474,ACIDENTE,BELÉM,PA,NaN,2015-09-13,13:17:00,0
2200,53550,53550,ACIDENTE,ITAPIPOCA,CE,NaN,2015-09-13,9:20:00,0
2201,53594,53594,INCIDENTE,CABO FRIO,RJ,SBCB,2015-09-14,13:00:00,0
2202,53608,53608,INCIDENTE,FLORIANÓPOLIS,SC,SBFL,2015-09-14,20:30:00,0
2203,53592,53592,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-09-15,14:50:00,0
2204,53593,53593,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-09-15,13:37:00,0
2205,53484,53484,ACIDENTE,ANGRA DOS REIS,RJ,NaN,2015-09-18,13:30:00,0
2206,53486,53486,ACIDENTE,GOIÂNIA,GO,SBGO,2015-09-19,13:20:00,1
2207,53487,53487,ACIDENTE,SANTA RITA DE CÁSSIA,BA,NaN,2015-09-19,20:30:00,0
2208,53482,53482,ACIDENTE,PIRENÓPOLIS,GO,SNMH,2015-09-20,21:10:00,0
2209,53483,53483,INCIDENTE,JUNDIAÍ,SP,SBJD,2015-09-20,21:05:00,0
2210,53485,53485,ACIDENTE,CASA BRANCA,SP,NaN,2015-09-20,17:30:00,0
2211,53606,53606,INCIDENTE,CARAUARI,AM,SWCA,2015-09-20,10:54:00,0
2212,53607,53607,INCIDENTE,RECIFE,PE,SBRF,2015-09-21,14:40:00,0
2213,53489,53489,ACIDENTE,JACAREACANGA,PA,SBEK,2015-09-22,22:15:00,0
2214,53506,53506,INCIDENTE,FOZ DO IGUAÇU,PR,SBFI,2015-09-22,15:57:00,0
2215,53488,53488,ACIDENTE,MACEIÓ,AL,NaN,2015-09-23,14:00:00,6
2216,53507,53507,INCIDENTE,FOZ DO IGUAÇU,PR,SBFI,2015-09-23,20:00:00,0
2217,53555,53555,ACIDENTE,CEARÁ-MIRIM,RN,SNOG,2015-09-23,13:00:00,0
2218,53554,53554,ACIDENTE,SANTA ROSA,RS,SSZR,2015-09-24,17:00:00,0
2219,53558,53558,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2015-09-25,22:15:00,0
2220,53610,53610,INCIDENTE,BAURU,SP,NaN,2015-09-25,10:08:00,0
2221,53503,53503,INCIDENTE,SANTARÉM,PA,SBSN,2015-09-26,11:45:00,0
2222,53495,53495,ACIDENTE,SANTO ANTÔNIO DO LEVERGER,MT,SWLV,2015-09-28,21:10:00,1
2223,53498,53498,ACIDENTE,ALTA FLORESTA,MT,NaN,2015-09-28,14:40:00,0
2224,53553,53553,ACIDENTE,TRAJANO DE MORAES,RJ,NaN,2015-09-28,18:30:00,0
2225,53609,53609,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2015-09-28,15:35:00,0
2226,53490,53490,INCIDENTE,SALVADOR,BA,SBSV,2015-09-30,4:30:00,0
2227,53491,53491,ACIDENTE,PAUINI,AM,NaN,2015-09-30,14:30:00,0
2228,53496,53496,INCIDENTE GRAVE,JATAÍ,GO,SWJW,2015-09-30,17:34:00,1
2229,53508,53508,INCIDENTE,FOZ DO IGUAÇU,PR,SBFI,2015-09-30,18:38:00,0
2230,53532,53532,INCIDENTE,GOIÂNIA,GO,SBGO,2015-09-30,11:55:00,0
2278,53563,53563,INCIDENTE GRAVE,TAIPU,RN,NaN,2015-09-11,20:00:00,0
2279,53564,53564,ACIDENTE,BALSAS,MA,SNBS,2015-09-11,19:30:00,4
2280,53566,53566,ACIDENTE,LENÇÓIS PAULISTA,SP,NaN,2015-09-11,19:30:00,0

In [33]:
#ocorrências do ano de 2015, mês 9, dia 4
filtro1 = df.ocorrencia_dia.dt.year == 2015
filtro2 = df.ocorrencia_dia.dt.month == 9
filtro3 = df.ocorrencia_dia.dt.day == 4
df.loc[filtro1 & filtro2 & filtro3]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
2016,53204,53204,INCIDENTE GRAVE,ANÁPOLIS,GO,SWNS,2015-09-04,13:13:00,3
2017,53208,53208,INCIDENTE,SÃO PAULO,SP,SBMT,2015-09-04,19:20:00,0

In [34]:
#ocorrências do dia 9 de setembro
filtro1 = df.ocorrencia_dia.dt.month == 9
filtro2 = df.ocorrencia_dia.dt.day == 4
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
839,47423,47423,INCIDENTE,SÃO PAULO,SP,SBSP,2013-09-04,15:45:00,0
840,47437,47437,INCIDENTE,BELÉM,PA,SBBE,2013-09-04,22:17:00,0
841,52967,52967,ACIDENTE,SINOP,MT,SWSI,2013-09-04,11:50:00,0
1484,50918,50918,ACIDENTE,AMERICANA,SP,SDAI,2014-09-04,14:40:00,0
1485,50921,50921,INCIDENTE,SANTANA DO PARAÍSO,MG,SBIP,2014-09-04,16:30:00,0
1486,50922,50922,INCIDENTE,FOZ DO IGUAÇU,PR,SBFI,2014-09-04,18:08:00,0
1487,50985,50985,ACIDENTE,PATOS DE MINAS,MG,NaN,2014-09-04,10:00:00,0
1488,51027,51027,INCIDENTE GRAVE,GUARULHOS,SP,SBGR,2014-09-04,16:17:00,3
1489,51031,51031,INCIDENTE GRAVE,MIRANORTE,TO,NaN,2014-09-04,17:30:00,0
2016,53204,53204,INCIDENTE GRAVE,ANÁPOLIS,GO,SWNS,2015-09-04,13:13:00,3
2017,53208,53208,INCIDENTE,SÃO PAULO,SP,SBMT,2015-09-04,19:20:00,0
2476,60983,60983,ACIDENTE,UIRAMUTÃ,RR,SJLO,2016-09-04,19:30:00,0
2477,60984,60984,ACIDENTE,TATUÍ,SP,SDTF,2016-09-04,15:14:00,0
2478,60998,60998,INCIDENTE,BELO HORIZONTE,MG,SBPR,2016-09-04,19:00:00,0
3308,77803,77803,INCIDENTE GRAVE,BRASÍLIA,DF,SBBR,2018-09-04,0:32:00,9
4276,79283,79283,INCIDENTE,SÃO PAULO,SP,SBMT,2020-09-04,14:30:00,0
4277,79303,79303,INCIDENTE,TAMBAÚ,SP,NaN,2020-09-04,13:00:00,0
4792,80017,80017,INCIDENTE GRAVE,GOIÂNIA,GO,NaN,2021-09-04,13:00:00,0
4793,80028,80028,INCIDENTE,BRASÍLIA,DF,SBBR,2021-09-04,18:32:00,0

In [36]:
#ocorrências do ano de 2015, mês 9, entre os dias 1 e 15
filtro1 = df.ocorrencia_dia.dt.year == 2015
filtro2 = df.ocorrencia_dia.dt.month == 9
filtro3 = (df.ocorrencia_dia.dt.day > 1) & (df.ocorrencia_dia.dt.day < 15) 
df.loc[filtro1 & filtro2 & filtro3]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
1932,52995,52995,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2015-09-02,10:00:00,0
1933,53000,53000,INCIDENTE,PORTO ALEGRE,RS,NaN,2015-09-02,9:00:00,0
2016,53204,53204,INCIDENTE GRAVE,ANÁPOLIS,GO,SWNS,2015-09-04,13:13:00,3
2017,53208,53208,INCIDENTE,SÃO PAULO,SP,SBMT,2015-09-04,19:20:00,0
2052,53255,53255,ACIDENTE,NOVO PROGRESSO,PA,SJNP,2015-09-05,17:30:00,0
2053,53258,53258,ACIDENTE,PARECI NOVO,RS,SSNG,2015-09-05,14:00:00,0
2054,53261,53261,ACIDENTE,MIRASSOL D'OESTE,MT,NaN,2015-09-05,20:00:00,0
2055,53285,53285,INCIDENTE,BELÉM,PA,SBBE,2015-09-05,12:53:00,0
2089,53308,53308,INCIDENTE GRAVE,SÃO LUÍS,MA,SBSL,2015-09-06,16:05:00,1
2127,53359,53359,ACIDENTE,TATUÍ,SP,SDTF,2015-09-07,16:15:00,0
2162,53424,53424,INCIDENTE,CURITIBA,PR,SBCT,2015-09-08,17:35:00,0
2163,53465,53465,ACIDENTE,PIRACANJUBA,GO,NaN,2015-09-08,12:30:00,0
2197,53480,53480,INCIDENTE,CONFINS,MG,SBCF,2015-09-09,14:00:00,0
2199,53474,53474,ACIDENTE,BELÉM,PA,NaN,2015-09-13,13:17:00,0
2200,53550,53550,ACIDENTE,ITAPIPOCA,CE,NaN,2015-09-13,9:20:00,0
2201,53594,53594,INCIDENTE,CABO FRIO,RJ,SBCB,2015-09-14,13:00:00,0
2202,53608,53608,INCIDENTE,FLORIANÓPOLIS,SC,SBFL,2015-09-14,20:30:00,0
2278,53563,53563,INCIDENTE GRAVE,TAIPU,RN,NaN,2015-09-11,20:00:00,0
2279,53564,53564,ACIDENTE,BALSAS,MA,SNBS,2015-09-11,19:30:00,4
2280,53566,53566,ACIDENTE,LENÇÓIS PAULISTA,SP,NaN,2015-09-11,19:30:00,0

In [42]:
df['ocorrencia_dia_hora'] = pd.to_datetime(df.ocorrencia_dia.astype(str) + ' ' + df.ocorrencia_hora)

In [43]:
df.head()

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
0,52242,52242,INCIDENTE,PORTO ALEGRE,RS,SBPA,2012-05-01,20:27:00,0,2012-05-01 20:27:00
1,45331,45331,ACIDENTE,GUARULHOS,SP,SBGR,2012-06-01,13:44:00,3,2012-06-01 13:44:00
2,45333,45333,ACIDENTE,VIAMÃO,RS,NaN,2012-06-01,13:00:00,0,2012-06-01 13:00:00
3,45401,45401,ACIDENTE,SÃO SEBASTIÃO,SP,NaN,2012-06-01,17:00:00,0,2012-06-01 17:00:00
4,45407,45407,ACIDENTE,SÃO SEPÉ,RS,NaN,2012-06-01,16:30:00,0,2012-06-01 16:30:00

In [44]:
df.dtypes

codigo_ocorrencia                    int64
codigo_ocorrencia2                   int64
ocorrencia_classificacao            object
ocorrencia_cidade                   object
ocorrencia_uf                       object
ocorrencia_aerodromo                object
ocorrencia_dia              datetime64[ns]
ocorrencia_hora                     object
total_recomendacoes                  int64
ocorrencia_dia_hora         datetime64[ns]
dtype: object

In [45]:
#ocorrências do ano de 2015, mês 9, entre os dias 1 e 15
filtro1 = df.ocorrencia_dia.dt.year == 2015
filtro2 = df.ocorrencia_dia.dt.month == 9
filtro3 = (df.ocorrencia_dia.dt.day > 1) & (df.ocorrencia_dia.dt.day < 15) 
df.loc[filtro1 & filtro2 & filtro3]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
1932,52995,52995,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2015-09-02,10:00:00,0,2015-09-02 10:00:00
1933,53000,53000,INCIDENTE,PORTO ALEGRE,RS,NaN,2015-09-02,9:00:00,0,2015-09-02 09:00:00
2016,53204,53204,INCIDENTE GRAVE,ANÁPOLIS,GO,SWNS,2015-09-04,13:13:00,3,2015-09-04 13:13:00
2017,53208,53208,INCIDENTE,SÃO PAULO,SP,SBMT,2015-09-04,19:20:00,0,2015-09-04 19:20:00
2052,53255,53255,ACIDENTE,NOVO PROGRESSO,PA,SJNP,2015-09-05,17:30:00,0,2015-09-05 17:30:00
2053,53258,53258,ACIDENTE,PARECI NOVO,RS,SSNG,2015-09-05,14:00:00,0,2015-09-05 14:00:00
2054,53261,53261,ACIDENTE,MIRASSOL D'OESTE,MT,NaN,2015-09-05,20:00:00,0,2015-09-05 20:00:00
2055,53285,53285,INCIDENTE,BELÉM,PA,SBBE,2015-09-05,12:53:00,0,2015-09-05 12:53:00
2089,53308,53308,INCIDENTE GRAVE,SÃO LUÍS,MA,SBSL,2015-09-06,16:05:00,1,2015-09-06 16:05:00
2127,53359,53359,ACIDENTE,TATUÍ,SP,SDTF,2015-09-07,16:15:00,0,2015-09-07 16:15:00
2162,53424,53424,INCIDENTE,CURITIBA,PR,SBCT,2015-09-08,17:35:00,0,2015-09-08 17:35:00
2163,53465,53465,ACIDENTE,PIRACANJUBA,GO,NaN,2015-09-08,12:30:00,0,2015-09-08 12:30:00
2197,53480,53480,INCIDENTE,CONFINS,MG,SBCF,2015-09-09,14:00:00,0,2015-09-09 14:00:00
2199,53474,53474,ACIDENTE,BELÉM,PA,NaN,2015-09-13,13:17:00,0,2015-09-13 13:17:00
2200,53550,53550,ACIDENTE,ITAPIPOCA,CE,NaN,2015-09-13,9:20:00,0,2015-09-13 09:20:00
2201,53594,53594,INCIDENTE,CABO FRIO,RJ,SBCB,2015-09-14,13:00:00,0,2015-09-14 13:00:00
2202,53608,53608,INCIDENTE,FLORIANÓPOLIS,SC,SBFL,2015-09-14,20:30:00,0,2015-09-14 20:30:00
2278,53563,53563,INCIDENTE GRAVE,TAIPU,RN,NaN,2015-09-11,20:00:00,0,2015-09-11 20:00:00
2279,53564,53564,ACIDENTE,BALSAS,MA,SNBS,2015-09-11,19:30:00,4,2015-09-11 19:30:00
2280,53566,53566,ACIDENTE,LENÇÓIS PAULISTA,SP,NaN,2015-09-11,19:30:00,0,2015-09-11 19:30:00

In [47]:
filtro1 = df.ocorrencia_dia_hora >= '2015-09-02 10:00:00'
filtro2 = df.ocorrencia_dia_hora <= '2015-09-11 19:30:00'
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
1932,52995,52995,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2015-09-02,10:00:00,0,2015-09-02 10:00:00
2016,53204,53204,INCIDENTE GRAVE,ANÁPOLIS,GO,SWNS,2015-09-04,13:13:00,3,2015-09-04 13:13:00
2017,53208,53208,INCIDENTE,SÃO PAULO,SP,SBMT,2015-09-04,19:20:00,0,2015-09-04 19:20:00
2052,53255,53255,ACIDENTE,NOVO PROGRESSO,PA,SJNP,2015-09-05,17:30:00,0,2015-09-05 17:30:00
2053,53258,53258,ACIDENTE,PARECI NOVO,RS,SSNG,2015-09-05,14:00:00,0,2015-09-05 14:00:00
2054,53261,53261,ACIDENTE,MIRASSOL D'OESTE,MT,NaN,2015-09-05,20:00:00,0,2015-09-05 20:00:00
2055,53285,53285,INCIDENTE,BELÉM,PA,SBBE,2015-09-05,12:53:00,0,2015-09-05 12:53:00
2089,53308,53308,INCIDENTE GRAVE,SÃO LUÍS,MA,SBSL,2015-09-06,16:05:00,1,2015-09-06 16:05:00
2127,53359,53359,ACIDENTE,TATUÍ,SP,SDTF,2015-09-07,16:15:00,0,2015-09-07 16:15:00
2162,53424,53424,INCIDENTE,CURITIBA,PR,SBCT,2015-09-08,17:35:00,0,2015-09-08 17:35:00
2163,53465,53465,ACIDENTE,PIRACANJUBA,GO,NaN,2015-09-08,12:30:00,0,2015-09-08 12:30:00
2197,53480,53480,INCIDENTE,CONFINS,MG,SBCF,2015-09-09,14:00:00,0,2015-09-09 14:00:00
2279,53564,53564,ACIDENTE,BALSAS,MA,SNBS,2015-09-11,19:30:00,4,2015-09-11 19:30:00
2280,53566,53566,ACIDENTE,LENÇÓIS PAULISTA,SP,NaN,2015-09-11,19:30:00,0,2015-09-11 19:30:00

In [49]:
#cocorrências do ano de 2015 e mês 03
filtro1 = df.ocorrencia_dia.dt.year == 2015
filtro2 = df.ocorrencia_dia.dt.month == 3

#criação do novo dataframe
df201503 = df.loc[filtro1 & filtro2]
df201503

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
1918,52988,52988,ACIDENTE,JOINVILLE,SC,SBJV,2015-03-02,17:45:00,1,2015-03-02 17:45:00
1919,52999,52999,INCIDENTE,ILHÉUS,BA,SBIL,2015-03-02,14:55:00,0,2015-03-02 14:55:00
1920,53105,53105,INCIDENTE GRAVE,SÃO MIGUEL DO IGUAÇU,PR,NaN,2015-03-02,20:00:00,0,2015-03-02 20:00:00
1969,53153,53153,INCIDENTE,PORTO ALEGRE,RS,SBPA,2015-03-13,15:45:00,0,2015-03-13 15:45:00
1970,53154,53154,INCIDENTE,SOROCABA,SP,SDCO,2015-03-13,14:40:00,0,2015-03-13 14:40:00
1971,53238,53238,INCIDENTE,SERRA,ES,NaN,2015-03-13,11:30:00,0,2015-03-13 11:30:00
1972,53189,53189,INCIDENTE,CONFINS,MG,SBCF,2015-03-14,7:20:00,0,2015-03-14 07:20:00
1973,53193,53193,ACIDENTE,CANARANA,MT,NaN,2015-03-14,18:00:00,0,2015-03-14 18:00:00
1974,53164,53164,ACIDENTE,PRINCESA ISABEL,PB,NaN,2015-03-15,18:30:00,0,2015-03-15 18:30:00
1975,53151,53151,INCIDENTE GRAVE,MAUÉS,AM,SWMW,2015-03-16,18:07:00,1,2015-03-16 18:07:00
1976,53168,53168,INCIDENTE,PARÁ DE MINAS,MG,SNPA,2015-03-16,21:05:00,0,2015-03-16 21:05:00
1977,53169,53169,INCIDENTE,BELÉM,PA,SBBE,2015-03-19,3:25:00,0,2015-03-19 03:25:00
1978,53165,53165,INCIDENTE GRAVE,SÃO DESIDÉRIO,BA,NaN,2015-03-20,14:35:00,0,2015-03-20 14:35:00
1979,53188,53188,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2015-03-20,21:00:00,0,2015-03-20 21:00:00
1980,53184,53184,ACIDENTE,PORTO UNIÃO,SC,NaN,2015-03-22,13:44:00,0,2015-03-22 13:44:00
1981,53178,53178,ACIDENTE,DIAMANTINO,MT,NaN,2015-03-23,17:15:00,0,2015-03-23 17:15:00
1982,53182,53182,ACIDENTE,SANTA LUZIA,MA,NaN,2015-03-23,20:40:00,0,2015-03-23 20:40:00
1983,53166,53166,INCIDENTE GRAVE,RIACHÃO DAS NEVES,BA,NaN,2015-03-24,14:45:00,0,2015-03-24 14:45:00
1984,53170,53170,INCIDENTE,CONFINS,MG,SBCF,2015-03-24,17:57:00,0,2015-03-24 17:57:00
1985,53185,53185,INCIDENTE,CURITIBA,PR,SBCT,2015-03-24,23:01:00,0,2015-03-24 23:01:00
1986,53412,53412,INCIDENTE GRAVE,MACAÉ,RJ,NaN,2015-03-24,16:35:00,0,2015-03-24 16:35:00
1987,53194,53194,ACIDENTE,GUARACIABA DO NORTE,CE,SWBE,2015-03-26,20:30:00,0,2015-03-26 20:30:00
1988,53186,53186,INCIDENTE,BRASÍLIA,DF,NaN,2015-03-27,14:55:00,0,2015-03-27 14:55:00
1989,53179,53179,ACIDENTE,CAIAPÔNIA,GO,NaN,2015-03-28,10:30:00,0,2015-03-28 10:30:00
1990,53180,53180,ACIDENTE,ARAGUARI,MG,NaN,2015-03-28,18:52:00,0,2015-03-28 18:52:00
1991,53190,53190,INCIDENTE,CAMPINAS,SP,SBKP,2015-03-28,16:26:00,0,2015-03-28 16:26:00
1992,53212,53212,INCIDENTE,JUNDIAÍ,SP,SBJD,2015-03-28,17:32:00,0,2015-03-28 17:32:00
1993,53213,53213,INCIDENTE,JUNDIAÍ,SP,SBJD,2015-03-28,15:51:00,0,2015-03-28 15:51:00
1994,53181,53181,ACIDENTE,COLÍDER,MT,NaN,2015-03-29,20:17:00,0,2015-03-29 20:17:00
1995,53187,53187,INCIDENTE,JOINVILLE,SC,SBJV,2015-03-29,18:36:00,0,2015-03-29 18:36:00
1996,53211,53211,INCIDENTE,BAURU,SP,SBBU,2015-03-30,19:40:00,0,2015-03-30 19:40:00
2000,53192,53192,ACIDENTE,BRAGANÇA PAULISTA,SP,SDVH,2015-03-04,14:30:00,0,2015-03-04 14:30:00
2043,53248,53248,INCIDENTE,FORTALEZA,CE,SBFZ,2015-03-05,15:00:00,0,2015-03-05 15:00:00
2117,53357,53357,INCIDENTE GRAVE,BELÉM,PA,SBJC,2015-03-07,13:35:00,0,2015-03-07 13:35:00
2235,53511,53511,INCIDENTE,MANAUS,AM,SWFN,2015-03-10,16:02:00,0,2015-03-10 16:02:00
2236,53512,53512,INCIDENTE,BRASÍLIA,DF,SBBR,2015-03-10,14:10:00,0,2015-03-10 14:10:00
2269,53587,53587,INCIDENTE,SÃO LUÍS,MA,SBSL,2015-03-11,17:20:00,0,2015-03-11 17:20:00
2306,53575,53575,INCIDENTE,CAMPOS DOS GOYTACAZES,RJ,SBFS,2015-03-12,10:50:00,0,2015-03-12 10:50:00
2307,60637,60637,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-03-12,16:47:00,0,2015-03-12 16:47:00

In [50]:
df201503.count()

codigo_ocorrencia           39
codigo_ocorrencia2          39
ocorrencia_classificacao    39
ocorrencia_cidade           39
ocorrencia_uf               39
ocorrencia_aerodromo        25
ocorrencia_dia              39
ocorrencia_hora             39
total_recomendacoes         39
ocorrencia_dia_hora         39
dtype: int64

In [51]:
df201503.groupby(['codigo_ocorrencia']).count()

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
codigo_ocorrencia,,,,,,,,,
52988,1,1,1,1,1,1,1,1,1
52999,1,1,1,1,1,1,1,1,1
53105,1,1,1,1,0,1,1,1,1
53151,1,1,1,1,1,1,1,1,1
53153,1,1,1,1,1,1,1,1,1
53154,1,1,1,1,1,1,1,1,1
53164,1,1,1,1,0,1,1,1,1
53165,1,1,1,1,0,1,1,1,1
53166,1,1,1,1,0,1,1,1,1
53168,1,1,1,1,1,1,1,1,1
53169,1,1,1,1,1,1,1,1,1
53170,1,1,1,1,1,1,1,1,1
53178,1,1,1,1,0,1,1,1,1
53179,1,1,1,1,0,1,1,1,1
53180,1,1,1,1,0,1,1,1,1
53181,1,1,1,1,0,1,1,1,1
53182,1,1,1,1,0,1,1,1,1
53184,1,1,1,1,0,1,1,1,1
53185,1,1,1,1,1,1,1,1,1
53186,1,1,1,1,0,1,1,1,1
53187,1,1,1,1,1,1,1,1,1
53188,1,1,1,1,1,1,1,1,1
53189,1,1,1,1,1,1,1,1,1
53190,1,1,1,1,1,1,1,1,1
53192,1,1,1,1,1,1,1,1,1
53193,1,1,1,1,0,1,1,1,1
53194,1,1,1,1,1,1,1,1,1
53211,1,1,1,1,1,1,1,1,1
53212,1,1,1,1,1,1,1,1,1
53213,1,1,1,1,1,1,1,1,1
53238,1,1,1,1,0,1,1,1,1
53248,1,1,1,1,1,1,1,1,1
53357,1,1,1,1,1,1,1,1,1
53412,1,1,1,1,0,1,1,1,1
53511,1,1,1,1,1,1,1,1,1
53512,1,1,1,1,1,1,1,1,1
53575,1,1,1,1,1,1,1,1,1
53587,1,1,1,1,1,1,1,1,1
60637,1,1,1,1,1,1,1,1,1

In [52]:
df201503.groupby(['codigo_ocorrencia']).codigo_ocorrencia.count()

codigo_ocorrencia
52988    1
52999    1
53105    1
53151    1
53153    1
53154    1
53164    1
53165    1
53166    1
53168    1
53169    1
53170    1
53178    1
53179    1
53180    1
53181    1
53182    1
53184    1
53185    1
53186    1
53187    1
53188    1
53189    1
53190    1
53192    1
53193    1
53194    1
53211    1
53212    1
53213    1
53238    1
53248    1
53357    1
53412    1
53511    1
53512    1
53575    1
53587    1
60637    1
Name: codigo_ocorrencia, dtype: int64

In [53]:
df201503.groupby(['ocorrencia_classificacao']).codigo_ocorrencia.count()

ocorrencia_classificacao
ACIDENTE           11
INCIDENTE          22
INCIDENTE GRAVE     6
Name: codigo_ocorrencia, dtype: int64

In [54]:
#observar porque não devemos contar por agrupamentos em colunas que apresentam valores nulos

df201503.groupby(['ocorrencia_classificacao']).ocorrencia_aerodromo.count()

ocorrencia_classificacao
ACIDENTE            3
INCIDENTE          20
INCIDENTE GRAVE     2
Name: ocorrencia_aerodromo, dtype: int64

In [55]:
df201503.groupby(['ocorrencia_classificacao']).size()

ocorrencia_classificacao
ACIDENTE           11
INCIDENTE          22
INCIDENTE GRAVE     6
dtype: int64

In [56]:
df201503.groupby(['ocorrencia_classificacao']).size().sort_values()

ocorrencia_classificacao
INCIDENTE GRAVE     6
ACIDENTE           11
INCIDENTE          22
dtype: int64

In [59]:
df201503.groupby(['ocorrencia_classificacao']).size().sort_values(ascending=False)

ocorrencia_classificacao
INCIDENTE          22
ACIDENTE           11
INCIDENTE GRAVE     6
dtype: int64

In [66]:
filtro1 = df.ocorrencia_dia.dt.year == 2013
filtro2 = df.ocorrencia_uf.isin(['SP','MG','SP','RJ','ES'])
dfsudeste2013 = df.loc[filtro1 & filtro2]
dfsudeste2013

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
647,46811,46811,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2013-01-01,4:45:00,0,2013-01-01 04:45:00
650,46782,46782,INCIDENTE,RIBEIRÃO PRETO,SP,SBRP,2013-03-01,20:00:00,0,2013-03-01 20:00:00
651,46857,46857,ACIDENTE,CARAGUATATUBA,SP,NaN,2013-03-01,16:00:00,0,2013-03-01 16:00:00
652,46783,46783,INCIDENTE,BELO HORIZONTE,MG,SBBH,2013-04-01,16:05:00,0,2013-04-01 16:05:00
653,46784,46784,INCIDENTE,CAMPINAS,SP,SBKP,2013-05-01,21:00:00,0,2013-05-01 21:00:00
...,...,...,...,...,...,...,...,...,...,...
1292,50390,50390,INCIDENTE,GUARULHOS,SP,SBGR,2013-12-26,23:40:00,0,2013-12-26 23:40:00
1293,50434,50434,INCIDENTE,SÃO PAULO,SP,SBMT,2013-12-27,15:26:00,0,2013-12-27 15:26:00
1294,50433,50433,INCIDENTE,BAIXO GUANDU,ES,SNBG,2013-12-28,12:45:00,0,2013-12-28 12:45:00
1296,50435,50435,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2013-12-29,20:07:00,0,2013-12-29 20:07:00
1300,50253,50253,ACIDENTE,NOVA PONTE,MG,NaN,2013-12-31,14:25:00,0,2013-12-31 14:25:00

In [67]:
dfsudeste2013.groupby(['ocorrencia_classificacao']).size()

ocorrencia_classificacao
ACIDENTE            71
INCIDENTE          203
INCIDENTE GRAVE     30
dtype: int64

In [68]:
dfsudeste2013.count()

codigo_ocorrencia           304
codigo_ocorrencia2          304
ocorrencia_classificacao    304
ocorrencia_cidade           304
ocorrencia_uf               304
ocorrencia_aerodromo        211
ocorrencia_dia              304
ocorrencia_hora             304
total_recomendacoes         304
ocorrencia_dia_hora         304
dtype: int64

In [69]:
dfsudeste2013.groupby(['ocorrencia_classificacao', 'ocorrencia_uf']).size()

ocorrencia_classificacao  ocorrencia_uf
ACIDENTE                  MG               10
                          RJ                8
                          SP               53
INCIDENTE                 ES               10
                          MG               38
                          RJ               63
                          SP               92
INCIDENTE GRAVE           ES                2
                          MG                9
                          RJ                6
                          SP               13
dtype: int64

In [70]:
dfsudeste2013.groupby(['ocorrencia_uf','ocorrencia_classificacao']).size()

ocorrencia_uf  ocorrencia_classificacao
ES             INCIDENTE                   10
               INCIDENTE GRAVE              2
MG             ACIDENTE                    10
               INCIDENTE                   38
               INCIDENTE GRAVE              9
RJ             ACIDENTE                     8
               INCIDENTE                   63
               INCIDENTE GRAVE              6
SP             ACIDENTE                    53
               INCIDENTE                   92
               INCIDENTE GRAVE             13
dtype: int64

In [73]:
dfsudeste2013.groupby(['ocorrencia_cidade']).size().sort_values(ascending=False)

ocorrencia_cidade
RIO DE JANEIRO    44
BELO HORIZONTE    22
CAMPINAS          17
SÃO PAULO         17
GUARULHOS         15
                  ..
ICÉM               1
HERCULÂNDIA        1
GUARUJÁ            1
GUARATINGUETÁ      1
VITÓRIA BRASIL     1
Length: 102, dtype: int64

In [74]:
filtro = dfsudeste2013.ocorrencia_cidade == 'RIO DE JANEIRO'
dfsudeste2013.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
647,46811,46811,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2013-01-01,4:45:00,0,2013-01-01 04:45:00
656,46812,46812,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2013-05-01,16:25:00,0,2013-05-01 16:25:00
667,46896,46896,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2013-11-01,18:30:00,0,2013-11-01 18:30:00
676,46866,46866,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2013-01-19,19:00:00,0,2013-01-19 19:00:00
721,47055,47055,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2013-09-02,14:00:00,0,2013-09-02 14:00:00
815,47309,47309,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2013-03-27,10:10:00,0,2013-03-27 10:10:00
821,47302,47302,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2013-03-28,10:48:00,0,2013-03-28 10:48:00
826,47299,47299,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2013-03-31,17:37:00,0,2013-03-31 17:37:00
829,51888,51888,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2013-01-04,14:15:00,0,2013-01-04 14:15:00
854,48105,48105,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2013-04-17,12:29:00,0,2013-04-17 12:29:00
859,48103,48103,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2013-04-18,17:45:00,0,2013-04-18 17:45:00
874,47894,47894,INCIDENTE GRAVE,RIO DE JANEIRO,RJ,SBRJ,2013-04-24,18:45:00,0,2013-04-24 18:45:00
881,48091,48091,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2013-04-27,12:56:00,0,2013-04-27 12:56:00
890,47983,47983,ACIDENTE,RIO DE JANEIRO,RJ,NaN,2013-02-05,19:00:00,5,2013-02-05 19:00:00
902,48012,48012,ACIDENTE,RIO DE JANEIRO,RJ,SDHU,2013-08-05,15:30:00,0,2013-08-05 15:30:00
932,48848,48848,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2013-05-22,13:20:00,0,2013-05-22 13:20:00
965,48850,48850,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2013-11-06,9:50:00,0,2013-11-06 09:50:00
967,48759,48759,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2013-06-14,9:42:00,0,2013-06-14 09:42:00
998,49258,49258,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2013-01-07,23:49:00,0,2013-01-07 23:49:00
1002,49264,49264,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2013-03-07,18:34:00,0,2013-03-07 18:34:00
1022,49286,49286,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2013-07-14,20:08:00,0,2013-07-14 20:08:00
1024,49279,49279,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2013-07-16,15:19:00,0,2013-07-16 15:19:00
1031,49294,49294,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2013-07-19,7:25:00,0,2013-07-19 07:25:00
1032,49537,49537,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2013-07-20,15:40:00,0,2013-07-20 15:40:00
1033,49693,49693,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2013-07-20,18:40:00,0,2013-07-20 18:40:00
1035,49532,49532,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2013-07-21,19:26:00,0,2013-07-21 19:26:00
1069,49523,49523,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2013-08-14,13:30:00,0,2013-08-14 13:30:00
1080,49529,49529,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2013-08-20,20:00:00,0,2013-08-20 20:00:00
1086,49538,49538,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2013-08-25,22:50:00,0,2013-08-25 22:50:00
1096,49621,49621,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2013-01-09,17:08:00,0,2013-01-09 17:08:00
1102,53104,53104,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2013-04-09,17:44:00,6,2013-04-09 17:44:00
1158,49958,49958,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2013-09-10,13:24:00,0,2013-09-10 13:24:00
1163,49962,49962,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2013-11-10,23:15:00,0,2013-11-10 23:15:00
1172,49966,49966,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2013-10-13,13:50:00,0,2013-10-13 13:50:00
1183,50211,50211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2013-10-19,14:40:00,0,2013-10-19 14:40:00
1189,50533,50533,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2013-10-23,19:15:00,0,2013-10-23 19:15:00
1194,50097,50097,INCIDENTE GRAVE,RIO DE JANEIRO,RJ,SBGL,2013-10-27,18:20:00,2,2013-10-27 18:20:00
1210,50260,50260,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2013-07-11,13:30:00,0,2013-07-11 13:30:00
1238,50374,50374,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2013-02-12,0:27:00,0,2013-02-12 00:27:00
1239,50375,50375,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2013-02-12,0:16:00,0,2013-02-12 00:16:00
1242,50559,50559,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2013-02-12,0:17:00,0,2013-02-12 00:17:00
1261,50376,50376,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2013-10-12,11:05:00,0,2013-10-12 11:05:00
1290,50389,50389,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2013-12-23,12:05:00,0,2013-12-23 12:05:00
1296,50435,50435,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2013-12-29,20:07:00,0,2013-12-29 20:07:00

In [75]:
filtro = dfsudeste2013.ocorrencia_cidade == 'RIO DE JANEIRO'
dfsudeste2013.loc[filtro].total_recomendacoes.sum()

13

In [76]:
filtro1 = dfsudeste2013.ocorrencia_cidade == 'RIO DE JANEIRO'
filtro2 = dfsudeste2013.total_recomendacoes > 0
dfsudeste2013.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
890,47983,47983,ACIDENTE,RIO DE JANEIRO,RJ,NaN,2013-02-05,19:00:00,5,2013-02-05 19:00:00
1102,53104,53104,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2013-04-09,17:44:00,6,2013-04-09 17:44:00
1194,50097,50097,INCIDENTE GRAVE,RIO DE JANEIRO,RJ,SBGL,2013-10-27,18:20:00,2,2013-10-27 18:20:00

In [77]:
dfsudeste2013.groupby(['ocorrencia_cidade']).total_recomendacoes.sum()

ocorrencia_cidade
ALFREDO CHAVES             0
AMERICANA                  0
ANDRADINA                  0
ARAGUARI                   0
ARARAS                     0
                          ..
VARGINHA                   0
VENDA NOVA DO IMIGRANTE    0
VILA VELHA                 0
VITÓRIA                    0
VITÓRIA BRASIL             0
Name: total_recomendacoes, Length: 102, dtype: int64

In [78]:
dfsudeste2013.groupby(['ocorrencia_aerodromo'], dropna=False).total_recomendacoes.sum()

ocorrencia_aerodromo
SBBH     0
SBBP     0
SBBU     0
SBCB     0
SBCF     0
        ..
SNGA     0
SNKF     0
SNKI     0
SNXI     0
NaN     27
Name: total_recomendacoes, Length: 67, dtype: int64

In [79]:
dfsudeste2013.groupby(['ocorrencia_cidade']).total_recomendacoes.sum()

ocorrencia_cidade
ALFREDO CHAVES             0
AMERICANA                  0
ANDRADINA                  0
ARAGUARI                   0
ARARAS                     0
                          ..
VARGINHA                   0
VENDA NOVA DO IMIGRANTE    0
VILA VELHA                 0
VITÓRIA                    0
VITÓRIA BRASIL             0
Name: total_recomendacoes, Length: 102, dtype: int64

In [80]:
filtro = dfsudeste2013.total_recomendacoes > 0
dfsudeste2013.loc[filtro].groupby(['ocorrencia_cidade']).total_recomendacoes.sum()

ocorrencia_cidade
CAMPO FLORIDO               2
CÂNDIDO MOTA                2
GUAPIAÇU                    1
GUARULHOS                   1
ICÉM                        1
ITANHAÉM                    1
JARINU                      1
JUNDIAÍ                     1
MACAÉ                       2
MANGARATIBA                 2
MARICÁ                      3
NOVA LIMA                   4
PERDIZES                    1
PROMISSÃO                   1
RIO CLARO                   1
RIO DE JANEIRO             13
SANTA CRUZ DO RIO PARDO     1
SOROCABA                    1
SÃO PAULO                   7
TAUBATÉ                     1
Name: total_recomendacoes, dtype: int64

In [81]:
filtro = dfsudeste2013.total_recomendacoes > 0
dfsudeste2013.loc[filtro].groupby(['ocorrencia_cidade']).total_recomendacoes.sum().sort_values()

ocorrencia_cidade
TAUBATÉ                     1
SOROCABA                    1
GUAPIAÇU                    1
GUARULHOS                   1
ICÉM                        1
ITANHAÉM                    1
JARINU                      1
JUNDIAÍ                     1
SANTA CRUZ DO RIO PARDO     1
RIO CLARO                   1
PROMISSÃO                   1
PERDIZES                    1
CAMPO FLORIDO               2
MACAÉ                       2
CÂNDIDO MOTA                2
MANGARATIBA                 2
MARICÁ                      3
NOVA LIMA                   4
SÃO PAULO                   7
RIO DE JANEIRO             13
Name: total_recomendacoes, dtype: int64

In [82]:
dfsudeste2013.loc[filtro].groupby(['ocorrencia_cidade', dfsudeste2013.ocorrencia_dia.dt.month]).total_recomendacoes.sum()

ocorrencia_cidade        ocorrencia_dia
CAMPO FLORIDO            1                 2
CÂNDIDO MOTA             3                 2
GUAPIAÇU                 2                 1
GUARULHOS                9                 1
ICÉM                     7                 1
ITANHAÉM                 3                 1
JARINU                   11                1
JUNDIAÍ                  3                 1
MACAÉ                    3                 2
MANGARATIBA              11                2
MARICÁ                   10                2
                         11                1
NOVA LIMA                6                 4
PERDIZES                 2                 1
PROMISSÃO                10                1
RIO CLARO                10                1
RIO DE JANEIRO           2                 5
                         4                 6
                         10                2
SANTA CRUZ DO RIO PARDO  7                 1
SOROCABA                 5                 1
SÃO PAULO                1                 1
                         5                 1
                         8                 5
TAUBATÉ                  3                 1
Name: total_recomendacoes, dtype: int64

In [84]:
filtro1 = dfsudeste2013.total_recomendacoes > 0
filtro2 = dfsudeste2013.ocorrencia_cidade == 'RIO DE JANEIRO'
dfsudeste2013.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
890,47983,47983,ACIDENTE,RIO DE JANEIRO,RJ,NaN,2013-02-05,19:00:00,5,2013-02-05 19:00:00
1102,53104,53104,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2013-04-09,17:44:00,6,2013-04-09 17:44:00
1194,50097,50097,INCIDENTE GRAVE,RIO DE JANEIRO,RJ,SBGL,2013-10-27,18:20:00,2,2013-10-27 18:20:00